global using global::CasCap.Common.Extensions;
global using global::CasCap.Exceptions;
global using global::CasCap.Interfaces;
global using global::CasCap.Messages;
global using global::CasCap.Models;
global using global::CasCap.Services;
global using global::Microsoft.Extensions.Configuration;
global using global::Microsoft.Extensions.Logging;
global using global::Microsoft.Extensions.Options;
