global using CasCap.Common.Extensions;
global using CasCap.Exceptions;
global using CasCap.Interfaces;
global using CasCap.Messages;
global using CasCap.Models;
global using CasCap.Services;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
