<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CasCap.Common.Net" Version="4.12.8" />
    <PackageVersion Include="CasCap.Common.Testing" Version="4.12.8" />
    <PackageVersion Include="Google.Apis.Auth" Version="1.76.0" />
    <PackageVersion Include="MetadataExtractor" Version="2.9.3" />
    <PackageVersion Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.10.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageVersion Include="MimeTypeMapOfficial" Version="1.0.17" />
    <PackageVersion Include="System.Threading.RateLimiting" Version="10.0.12" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
</Project>