#ctl+alt+r

###

POST https://photoslibrary.googleapis.com/v1/uploads
Authorization: Bearer xyz
Content-Length: 0
X-Goog-Upload-Command: start
X-Goog-Upload-Content-Type: image/jpeg
X-Goog-Upload-File-Name: test.png
X-Goog-Upload-Protocol: resumable
X-Goog-Upload-Raw-Size: 4096000